Feature/#180
Kota8102/diary-app pull request #181
Opened 2024-08-19 03:18 UTC by mt-osho-san

## 概要

タイトルを取得するAPIで該当するデータが無いときに404が返る様になっていた部分を空のデータを200番で返すように修正

## 変更点

このセクションでは、具体的な変更点や修正箇所を箇条書きでリストアップしてください。

- データが空の場合の処理を200番で返すようにしました。

## 影響範囲

このセクションでは、この PR が影響を及ぼす範囲や他の機能への影響を説明してください。

- タイトルを取得するAPIを叩くフロントエンドの処理において、タイトルがない場合にこれまで404エラーが返るようになっていた部分が200番が返るようになります。

## テスト

このセクションでは、この PR に関連するテストケースやテスト方法を記載してください。

- 別IssueでAPIのテストを作成します

## 関連 Issue

このセクションでは、この PR が関連する Issue やタスクをリンクしてください。以下のように記述します。

- 関連 Issue: #180

2024-08-20 05:32 UTC, Kota8102 requested changes

2024-08-20 05:32 UTC, Kota8102 commented on src/backend/lambda/title_get/title_get.py
lambda handlerにコメントは？
必要な引数おbodyの中身はあってもいいかな

2024-08-21 14:19 UTC, mt-osho-san commented
Pytest追記しました。

2024-09-11 10:57 UTC, Kota8102 approved these changes

2024-09-11 11:58 UTC, merged